import { MapSimple } from "@/interface/map";
export * from "./_view";
export * from "./_viewMap";
export * from "./_viewMapMarker";
export * from "./_measurement";
export * from "./_measureDistance";
export * from "./_measureArea";
export * from "./_measureAzimuth";
export * from "./_measurePoint";
export * from "./_handle";
export declare function addCursorCrosshair(map: MapSimple): void;
export declare function removeCursorCrosshair(map: MapSimple): void;
